included:
  - AIQuizlet/Sources
excluded:
  - Pods
  - AIQuizlet/DerivedData
  - AIQuizletTests
  - Tuist
disabled_rules:
  - line_length
  - trailing_whitespace
  - force_cast
  - force_try
  - function_body_length
  - type_body_length
  - file_length
